# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import json
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
data_file = "city_data.csv"
df = pd.read_csv(data_file)
df.head()

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,Rikitea,-23.12,-134.97,294.35,78,75,10.52,PF,1601442538
1,1,Provideniya,64.38,-173.30,280.15,65,90,3.00,RU,1601442539
2,2,Lebu,-37.62,-73.65,280.94,83,95,5.02,CL,1601442247
3,3,Aragarças,-15.90,-52.25,299.78,24,20,0.78,BR,1601442539
4,4,Ranfurly,-45.13,170.10,281.48,59,66,1.34,NZ,1601442539

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
# Create a list containing coordinates
coordinates = df[['Lat', 'Lng']].astype(float)
humidity = df["Humidity"].astype(float)

In [13]:
# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(coordinates, weights=humidity, dissipating=False, max_intensity=10,
                                 point_radius=1)


# Add layer
fig.add_layer(heat_layer)

# Display figure
fig
plt.savefig("Images/HumidityHeatmap.png")

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [5]:
# Narrow cities with Wind speed less than 15 mph.
# Zero cloudiness
# Humidity lower than 25
new_df = df.loc[df["Wind Speed"] < 15]
good_df = new_df.loc[new_df["Cloudiness"] == 0]
ideal_df = good_df.loc[good_df["Humidity"] < 25]
ideal_df

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
23,23,Aswān,24.09,32.91,302.97,21,0,3.63,EG,1601442545
166,166,Alice Springs,-23.70,133.88,301.15,24,0,4.10,AU,1601442586
198,198,Taoudenni,22.68,-3.98,304.77,13,0,2.15,ML,1601442595
287,287,Tessalit,20.20,1.01,301.60,15,0,2.46,ML,1601442786
305,305,Madera,37.17,-119.83,300.37,23,0,0.45,US,1601442792
357,357,Gangānagar,29.92,73.88,307.40,19,0,2.77,IN,1601442807
418,418,Wana,32.30,69.57,296.48,20,0,6.71,PK,1601442825

In [6]:
hotel_df = ideal_df

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [7]:
# Using Google Places API to find the first hotel for each city located within 5000 meters of your coordinates.
# geocoordinates
target_radius = 5000
target_type = "lodging"

# Build URL using the Google Maps API
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

# Build parameters
params = {"types": target_type, "radius": target_radius, "key": g_key}


for index, row in ideal_df.iterrows():
    # Get coordinates
    city = row["City"]
    lat = row["Lat"]
    lng = row["Lng"]
    

    # change location each iteration while leaving original params in place
    params["location"] = f"{lat},{lng}"

    # Make API request  
    response = requests.get(base_url, params=params).json()
    
    # extract results
    results = response['results']
    
    try:
        print(f"In {city}, the first hotel is {results[0]['name']}.")
        hotel_df.loc[index, 'Hotel Name'] = results[0]['name']
        
    except (KeyError, IndexError):
        print("Hotel not found. Skipping....")

In Aswān, the first hotel is Nuba Nile.

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:845: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

In Alice Springs, the first hotel is Desert Palms Alice Springs.
Hotel not found. Skipping....
Hotel not found. Skipping....
Hotel not found. Skipping....
In Gangānagar, the first hotel is Amor hotel.
In Wana, the first hotel is Rest House at Wana Camp.

In [8]:
hotel_df

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
23,23,Aswān,24.09,32.91,302.97,21,0,3.63,EG,1601442545,Nuba Nile
166,166,Alice Springs,-23.70,133.88,301.15,24,0,4.10,AU,1601442586,Desert Palms Alice Springs
198,198,Taoudenni,22.68,-3.98,304.77,13,0,2.15,ML,1601442595,NaN
287,287,Tessalit,20.20,1.01,301.60,15,0,2.46,ML,1601442786,NaN
305,305,Madera,37.17,-119.83,300.37,23,0,0.45,US,1601442792,NaN
357,357,Gangānagar,29.92,73.88,307.40,19,0,2.77,IN,1601442807,Amor hotel
418,418,Wana,32.30,69.57,296.48,20,0,6.71,PK,1601442825,Rest House at Wana Camp

In [9]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [14]:
# Create hotel symbol layer
markers = gmaps.marker_layer(locations)
hotel_layer = gmaps.symbol_layer(
    locations, fill_color='rgba(0, 150, 0, 0.4)',
    stroke_color='rgba(0, 0, 150, 0.4)', scale=2,
    info_box_content=hotel_info)
    
# Add marker layer ontop of heat map
fig.add_layer(markers)
fig.add_layer(hotel_layer)

# Display figure
fig
plt.savefig("Images/HotelMap.png")